import { Activity, Camera, ClipboardList, Contrast, Droplets, Eye, ScanEye, Sparkles } from 'lucide-react'

// One source for the test library, home shortcuts, and exam navigation.
export const TEST_CATALOG = [
  { id: 'blink-rate', title: 'Count my blinks', clinical: 'Blink rate', description: 'Look at the camera for 30 seconds. See how often you blink.', icon: Activity, color: 'mint', tag: '30 seconds', steps: ['Press Turn camera on and keep your face in view.', 'Press Count my blinks. Blink naturally for 30 seconds.', 'Your blink count and rate appear when the timer ends.'] },
  { id: 'meibography', title: 'Check eye glands', clinical: 'Meibography', description: 'Upload an eyelid image to review the tiny glands that help protect your eyes.', icon: ScanEye, color: 'blue', tag: 'Image analysis', steps: ['Choose a patient, eye, and eyelid.', 'Upload a clear eyelid image or take a photo.', 'Select the gland area and press Analyze to see results.'] },
  { id: 'tear-meniscus', title: 'Measure tears', clinical: 'Tear meniscus', description: 'Use an eye image to measure the small strip of tears below the eye.', icon: Droplets, color: 'sky', tag: 'Image measurement', steps: ['Choose the lower eyelid and add a clear photo.', 'Mark the tear strip on the image.', 'Review the measurement and save it to the report.'] },
  { id: 'bulbar-redness', title: 'Check eye redness', clinical: 'Bulbar redness', description: 'Compare an eye photo with a simple redness scale.', icon: Eye, color: 'rose', tag: 'Photo comparison', steps: ['Add a photo of the eye.', 'Choose the reference image that looks most similar.', 'Save the selected redness grade.'] },
  { id: 'deq', title: 'How do my eyes feel?', clinical: 'DEQ-5 questionnaire', description: 'Answer five simple questions about dryness and discomfort.', icon: ClipboardList, color: 'amber', tag: '5 questions', steps: ['Read each question about how your eyes feel.', 'Choose the answer that fits best.', 'Press Save to calculate the questionnaire score.'] },
  { id: 'osdi', title: 'Eyes in everyday life', clinical: 'OSDI questionnaire', description: 'Tell us how your eyes feel during everyday activities.', icon: Sparkles, color: 'violet', tag: '12 questions', steps: ['Think about your eyes over the past week.', 'Answer each question, or choose N/A where available.', 'Save your answers to see the questionnaire score.'] },
  { id: 'contrast-sensitivity', title: 'Check light and dark', clinical: 'Contrast sensitivity', description: 'Record how clearly you can see patterns at different contrast levels.', icon: Contrast, color: 'slate', tag: 'Record test values', steps: ['Choose the test type.', 'Enter the measured values from a contrast test.', 'Review the calculated summary and save it.'] },
  { id: 'posterior-segment', title: 'Review the back of the eye', clinical: 'Posterior segment', description: 'Add findings and recommendations from an eye examination.', icon: Camera, color: 'blue', tag: 'Clinical notes', steps: ['Choose the eye you examined.', 'Add findings and a recommendation.', 'Save your notes for the report.'] },
]

export const getTestUrl = id => `/eye-test/meibography?section=${encodeURIComponent(id)}`
